--- 

- hosts: all
  become: true
  tasks:

  - name: install apache and php packages for Debian/Ubuntu
    apt:
      update_cache: yes
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: install apache and php packages for CentOS
    dnf:
      update_cache: yes
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"
