--- 

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Debian, Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false  
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: install updates (CentOS)
    tags: always
    dnf: 
      update_cache: yes
    changed_when: false  
    when: ansible_distribution == "CentOS"

- hosts: all
  become: true
  roles:
    - base

- hosts: web_servers
  become: true
  roles:
    - web_servers
  
  
- hosts: file_servers
  become: true
  roles:
    - file_servers
